export const GET_NEXT_QUESTION = 'GET_NEXT_QUESTION';
export const GET_PREV_QUESTION = 'GET_PREV_QUESTION';
export const TOGGLE_VISIBILITY = 'TOGGLE_VISIBILITY';
export const SET_CURRENT_COUNTRY = 'SET_CURRENT_COUNTRY';