export const GET_NEXT_QUESTION = 'GET_NEXT_QUESTION';
export const GET_PREV_QUESTION = 'GET_PREV_QUESTION';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const SET_CURRENT_COUNTRY = 'SET_CURRENT_COUNTRY';